name: Docker Image CI

on: 
  push:
    branches:
      [ beta ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: thezeldaboi/wynnbot:beta
        build-args: |
            TESTING=${{ secrets.TESTING_TOKEN }}
            DISCORD=${{ secrets.DISCORD_TOKEN }}
            
    - name: Start SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ubuntu
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull thezeldaboi/wynnbot:beta
          docker run -d --name beta thezeldaboi/wynnbot:beta
