name: Docker Image CI

on:
  push:
    branches: [ beta, main ]
  pull_request:
    branches: [ beta, main ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: thezeldaboi/wynnbot:beta
        build-args: |
            TESTING=${{ secrets.TESTING_TOKEN }}
            DISCORD=${{ secrets.DISCORD_TOKEN }}
