name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches: [beta]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: thezeldaboi/wynnbot
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secret:  |
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            TESTING_TOKEN=${{ secrets.TESTING_TOKEN }}
