name: Docker Image CI

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build
      uses: docker/build-push-action@v2
      with:
        tags: thezeldaboi/wynnbot:beta
        secrets: |
            TESTING_TOKEN=${{ secrets.TESTING_TOKEN }}"
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}"
